# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "candle"
  s.version = "0.0.6"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Eiffel Qiu"]
  s.date = "2013-03-07"
  s.description = "Wax iOS Starter Project Generate Tools build with Ruby"
  s.email = "eiffelqiu@gmail.com"
  s.executables = ["candle"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "LICENSE.txt",
    "README.md",
    "VERSION",
    "lib/candle.rb",
    "lib/candle/command.rb",
    "lib/candle/generators/actions.rb",
    "lib/candle/generators/blank.rb",
    "lib/candle/generators/cli.rb",
    "lib/candle/generators/help.rb",
    "lib/candle/generators/jam.rb",
    "lib/candle/generators/lua/wax/ProtocolLoader.h",
    "lib/candle/generators/lua/wax/bin/hammer",
    "lib/candle/generators/lua/wax/bin/update-xibs",
    "lib/candle/generators/lua/wax/bin/waxsim",
    "lib/candle/generators/lua/wax/lib/build-scripts/compile-stdlib.sh",
    "lib/candle/generators/lua/wax/lib/build-scripts/copy-scripts.sh",
    "lib/candle/generators/lua/wax/lib/build-scripts/luac.lua",
    "lib/candle/generators/lua/wax/lib/extensions/CGAffine/wax_CGTransform.h",
    "lib/candle/generators/lua/wax/lib/extensions/CGAffine/wax_CGTransform.m",
    "lib/candle/generators/lua/wax/lib/extensions/CGContext/wax_CGContext.h",
    "lib/candle/generators/lua/wax/lib/extensions/CGContext/wax_CGContext.m",
    "lib/candle/generators/lua/wax/lib/extensions/HTTP/wax_http.h",
    "lib/candle/generators/lua/wax/lib/extensions/HTTP/wax_http.m",
    "lib/candle/generators/lua/wax/lib/extensions/HTTP/wax_http_connection.h",
    "lib/candle/generators/lua/wax/lib/extensions/HTTP/wax_http_connection.m",
    "lib/candle/generators/lua/wax/lib/extensions/filesystem/wax_filesystem.h",
    "lib/candle/generators/lua/wax/lib/extensions/filesystem/wax_filesystem.m",
    "lib/candle/generators/lua/wax/lib/extensions/json/Rakefile",
    "lib/candle/generators/lua/wax/lib/extensions/json/wax_json.c",
    "lib/candle/generators/lua/wax/lib/extensions/json/wax_json.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl-1.0.9.tar.gz",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/api/yajl_common.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/api/yajl_gen.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/api/yajl_parse.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl.c",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_alloc.c",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_alloc.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_buf.c",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_buf.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_bytestack.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_common.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_encode.c",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_encode.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_gen.c",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_gen.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_lex.c",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_lex.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_parse.h",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_parser.c",
    "lib/candle/generators/lua/wax/lib/extensions/json/yajl/yajl_parser.h",
    "lib/candle/generators/lua/wax/lib/lua/lapi.c",
    "lib/candle/generators/lua/wax/lib/lua/lapi.h",
    "lib/candle/generators/lua/wax/lib/lua/lauxlib.c",
    "lib/candle/generators/lua/wax/lib/lua/lauxlib.h",
    "lib/candle/generators/lua/wax/lib/lua/lbaselib.c",
    "lib/candle/generators/lua/wax/lib/lua/lcode.c",
    "lib/candle/generators/lua/wax/lib/lua/lcode.h",
    "lib/candle/generators/lua/wax/lib/lua/ldblib.c",
    "lib/candle/generators/lua/wax/lib/lua/ldebug.c",
    "lib/candle/generators/lua/wax/lib/lua/ldebug.h",
    "lib/candle/generators/lua/wax/lib/lua/ldo.c",
    "lib/candle/generators/lua/wax/lib/lua/ldo.h",
    "lib/candle/generators/lua/wax/lib/lua/ldump.c",
    "lib/candle/generators/lua/wax/lib/lua/lfunc.c",
    "lib/candle/generators/lua/wax/lib/lua/lfunc.h",
    "lib/candle/generators/lua/wax/lib/lua/lgc.c",
    "lib/candle/generators/lua/wax/lib/lua/lgc.h",
    "lib/candle/generators/lua/wax/lib/lua/linit.c",
    "lib/candle/generators/lua/wax/lib/lua/liolib.c",
    "lib/candle/generators/lua/wax/lib/lua/llex.c",
    "lib/candle/generators/lua/wax/lib/lua/llex.h",
    "lib/candle/generators/lua/wax/lib/lua/llimits.h",
    "lib/candle/generators/lua/wax/lib/lua/lmathlib.c",
    "lib/candle/generators/lua/wax/lib/lua/lmem.c",
    "lib/candle/generators/lua/wax/lib/lua/lmem.h",
    "lib/candle/generators/lua/wax/lib/lua/loadlib.c",
    "lib/candle/generators/lua/wax/lib/lua/lobject.c",
    "lib/candle/generators/lua/wax/lib/lua/lobject.h",
    "lib/candle/generators/lua/wax/lib/lua/lopcodes.c",
    "lib/candle/generators/lua/wax/lib/lua/lopcodes.h",
    "lib/candle/generators/lua/wax/lib/lua/loslib.c",
    "lib/candle/generators/lua/wax/lib/lua/lparser.c",
    "lib/candle/generators/lua/wax/lib/lua/lparser.h",
    "lib/candle/generators/lua/wax/lib/lua/lstate.c",
    "lib/candle/generators/lua/wax/lib/lua/lstate.h",
    "lib/candle/generators/lua/wax/lib/lua/lstring.c",
    "lib/candle/generators/lua/wax/lib/lua/lstring.h",
    "lib/candle/generators/lua/wax/lib/lua/lstrlib.c",
    "lib/candle/generators/lua/wax/lib/lua/ltable.c",
    "lib/candle/generators/lua/wax/lib/lua/ltable.h",
    "lib/candle/generators/lua/wax/lib/lua/ltablib.c",
    "lib/candle/generators/lua/wax/lib/lua/ltm.c",
    "lib/candle/generators/lua/wax/lib/lua/ltm.h",
    "lib/candle/generators/lua/wax/lib/lua/lua.h",
    "lib/candle/generators/lua/wax/lib/lua/luaconf.h",
    "lib/candle/generators/lua/wax/lib/lua/lualib.h",
    "lib/candle/generators/lua/wax/lib/lua/lundump.c",
    "lib/candle/generators/lua/wax/lib/lua/lundump.h",
    "lib/candle/generators/lua/wax/lib/lua/lvm.c",
    "lib/candle/generators/lua/wax/lib/lua/lvm.h",
    "lib/candle/generators/lua/wax/lib/lua/lzio.c",
    "lib/candle/generators/lua/wax/lib/lua/lzio.h",
    "lib/candle/generators/lua/wax/lib/lua/print.c",
    "lib/candle/generators/lua/wax/lib/project.rake",
    "lib/candle/generators/lua/wax/lib/stdlib/enums.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/ext/http.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/ext/init.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/ext/number.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/ext/string.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/ext/table.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/helpers/WaxServer.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/helpers/autoload.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/helpers/base64.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/helpers/bit.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/helpers/cache.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/helpers/callback.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/helpers/frame.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/helpers/init.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/helpers/pickView.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/helpers/time.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/init.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/luaspec/init.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/luaspec/luamock.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/luaspec/luaspec.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/repl.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/structs.lua",
    "lib/candle/generators/lua/wax/lib/stdlib/waxClass.lua",
    "lib/candle/generators/lua/wax/lib/wax.h",
    "lib/candle/generators/lua/wax/lib/wax.m",
    "lib/candle/generators/lua/wax/lib/wax_class.h",
    "lib/candle/generators/lua/wax/lib/wax_class.m",
    "lib/candle/generators/lua/wax/lib/wax_gc.h",
    "lib/candle/generators/lua/wax/lib/wax_gc.m",
    "lib/candle/generators/lua/wax/lib/wax_helpers.h",
    "lib/candle/generators/lua/wax/lib/wax_helpers.m",
    "lib/candle/generators/lua/wax/lib/wax_instance.h",
    "lib/candle/generators/lua/wax/lib/wax_instance.m",
    "lib/candle/generators/lua/wax/lib/wax_server.h",
    "lib/candle/generators/lua/wax/lib/wax_server.m",
    "lib/candle/generators/lua/wax/lib/wax_stdlib.h",
    "lib/candle/generators/lua/wax/lib/wax_struct.h",
    "lib/candle/generators/lua/wax/lib/wax_struct.m",
    "lib/candle/generators/table.rb",
    "lib/candle/generators/templates/blank/WaxApplication.xcodeproj/project.pbxproj",
    "lib/candle/generators/templates/blank/WaxApplication.xcodeproj/project.xcworkspace/contents.xcworkspacedata",
    "lib/candle/generators/templates/blank/WaxApplication.xcodeproj/project.xcworkspace/xcuserdata/eiffel.xcuserdatad/UserInterfaceState.xcuserstate",
    "lib/candle/generators/templates/blank/WaxApplication.xcodeproj/xcuserdata/eiffel.xcuserdatad/xcschemes/WaxApplication.xcscheme",
    "lib/candle/generators/templates/blank/WaxApplication.xcodeproj/xcuserdata/eiffel.xcuserdatad/xcschemes/xcschememanagement.plist",
    "lib/candle/generators/templates/blank/WaxApplication/ProtocolLoader.h",
    "lib/candle/generators/templates/blank/WaxApplication/WaxApplication-Info.plist.tt",
    "lib/candle/generators/templates/blank/WaxApplication/WaxApplication-Prefix.pch.tt",
    "lib/candle/generators/templates/blank/WaxApplication/en.lproj/InfoPlist.strings",
    "lib/candle/generators/templates/blank/WaxApplication/main.m.tt",
    "lib/candle/generators/templates/blank/scripts/AppDelegate.lua",
    "lib/candle/generators/templates/blank/scripts/tests/init.lua",
    "lib/candle/generators/templates/blank/scripts/tests/someTest.lua",
    "lib/candle/generators/templates/project.rake",
    "lib/candle/generators/templates/resources/Default-568h@2x.png",
    "lib/candle/generators/templates/resources/Default.png",
    "lib/candle/generators/templates/resources/Default@2x.png",
    "lib/candle/generators/templates/table/WaxApplication.xcodeproj/project.pbxproj",
    "lib/candle/generators/templates/table/WaxApplication.xcodeproj/project.xcworkspace/contents.xcworkspacedata",
    "lib/candle/generators/templates/table/WaxApplication.xcodeproj/project.xcworkspace/xcuserdata/eiffel.xcuserdatad/UserInterfaceState.xcuserstate",
    "lib/candle/generators/templates/table/WaxApplication.xcodeproj/xcuserdata/eiffel.xcuserdatad/xcschemes/WaxApplication.xcscheme",
    "lib/candle/generators/templates/table/WaxApplication.xcodeproj/xcuserdata/eiffel.xcuserdatad/xcschemes/xcschememanagement.plist",
    "lib/candle/generators/templates/table/WaxApplication/ProtocolLoader.h",
    "lib/candle/generators/templates/table/WaxApplication/WaxApplication-Info.plist.tt",
    "lib/candle/generators/templates/table/WaxApplication/WaxApplication-Prefix.pch.tt",
    "lib/candle/generators/templates/table/WaxApplication/en.lproj/InfoPlist.strings",
    "lib/candle/generators/templates/table/WaxApplication/main.m.tt",
    "lib/candle/generators/templates/table/scripts/AppDelegate.lua",
    "lib/candle/generators/templates/table/scripts/CapitalsTable.lua",
    "lib/candle/generators/templates/table/scripts/StatesTable.lua",
    "lib/candle/generators/templates/table/scripts/states.plist",
    "lib/candle/generators/templates/table/scripts/tests/init.lua",
    "lib/candle/generators/templates/table/scripts/tests/someTest.lua",
    "lib/candle/generators/templates/xib/WaxApplication.xcodeproj/project.pbxproj",
    "lib/candle/generators/templates/xib/WaxApplication.xcodeproj/project.xcworkspace/contents.xcworkspacedata",
    "lib/candle/generators/templates/xib/WaxApplication.xcodeproj/project.xcworkspace/xcuserdata/eiffel.xcuserdatad/UserInterfaceState.xcuserstate",
    "lib/candle/generators/templates/xib/WaxApplication.xcodeproj/xcuserdata/eiffel.xcuserdatad/xcschemes/WaxApplication.xcscheme",
    "lib/candle/generators/templates/xib/WaxApplication.xcodeproj/xcuserdata/eiffel.xcuserdatad/xcschemes/xcschememanagement.plist",
    "lib/candle/generators/templates/xib/WaxApplication/ProtocolLoader.h",
    "lib/candle/generators/templates/xib/WaxApplication/WaxApplication-Info.plist.tt",
    "lib/candle/generators/templates/xib/WaxApplication/WaxApplication-Prefix.pch.tt",
    "lib/candle/generators/templates/xib/WaxApplication/en.lproj/InfoPlist.strings",
    "lib/candle/generators/templates/xib/WaxApplication/main.m.tt",
    "lib/candle/generators/templates/xib/scripts/AppDelegate.lua",
    "lib/candle/generators/templates/xib/scripts/BlueViewController.lua",
    "lib/candle/generators/templates/xib/scripts/BlueViewController.xib",
    "lib/candle/generators/templates/xib/scripts/OrangeViewController.lua",
    "lib/candle/generators/templates/xib/scripts/OrangeViewController.xib",
    "lib/candle/generators/templates/xib/scripts/tests/init.lua",
    "lib/candle/generators/templates/xib/scripts/tests/someTest.lua",
    "lib/candle/generators/xib.rb",
    "lib/candle/tasks.rb",
    "lib/candle/utility.rb",
    "lib/candle/version.rb",
    "lib/candle/view.rb"
  ]
  s.homepage = "http://github.com/eiffelqiu/candle"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Wax iOS Starter Project Generate Tools"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<cli-colorize>, [">= 0"])
      s.add_runtime_dependency(%q<hirb>, [">= 0"])
      s.add_runtime_dependency(%q<plist>, [">= 0"])
      s.add_development_dependency(%q<riot>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<grit>, [">= 0"])
      s.add_development_dependency(%q<i18n>, [">= 0"])
      s.add_development_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_development_dependency(%q<uuid>, [">= 2.3.1"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.2.8"])
      s.add_runtime_dependency(%q<grit>, [">= 0"])
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
      s.add_runtime_dependency(%q<hirb>, [">= 0"])
      s.add_runtime_dependency(%q<cli-colorize>, [">= 0"])
      s.add_runtime_dependency(%q<rdoc>, [">= 0"])
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<plist>, [">= 0"])
    else
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<cli-colorize>, [">= 0"])
      s.add_dependency(%q<hirb>, [">= 0"])
      s.add_dependency(%q<plist>, [">= 0"])
      s.add_dependency(%q<riot>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.1.3"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<grit>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
      s.add_dependency(%q<uuid>, [">= 2.3.1"])
      s.add_dependency(%q<activesupport>, [">= 3.2.8"])
      s.add_dependency(%q<grit>, [">= 0"])
      s.add_dependency(%q<i18n>, [">= 0"])
      s.add_dependency(%q<hirb>, [">= 0"])
      s.add_dependency(%q<cli-colorize>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<yajl-ruby>, [">= 0"])
      s.add_dependency(%q<plist>, [">= 0"])
    end
  else
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<cli-colorize>, [">= 0"])
    s.add_dependency(%q<hirb>, [">= 0"])
    s.add_dependency(%q<plist>, [">= 0"])
    s.add_dependency(%q<riot>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.1.3"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.4"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<grit>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.8"])
    s.add_dependency(%q<uuid>, [">= 2.3.1"])
    s.add_dependency(%q<activesupport>, [">= 3.2.8"])
    s.add_dependency(%q<grit>, [">= 0"])
    s.add_dependency(%q<i18n>, [">= 0"])
    s.add_dependency(%q<hirb>, [">= 0"])
    s.add_dependency(%q<cli-colorize>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<yajl-ruby>, [">= 0"])
    s.add_dependency(%q<plist>, [">= 0"])
  end
end

